spring:
  application:
    name: firstSpringBoot
stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: USD,EUR,GBP

payment-gateway: paypal

datasource:
    url: jdbc:mysql://localhost:3306/myDatabase?
    username: root
    password: Pa$$w0rd
    driver-class-name: com.mysql.cj.jdbc.Driver